const createConsumableHandler = require('./create')
const deleteConsumableHandler = require('./delete')
const updateConsumableHandler = require('./update')
const assignConsumableHandler = require('./assign')
const historyConsumableHandler = require('./history')
const entireHistoryConsumableHandler = require('./entireHistory')
const listConsumableHandler = require('./list')
const updateConsumablePurchaseHandler = require('./editpurchase')
const admintokenAuth = require('../../middleware/admintokenAuth')
const listConsumableNameHandler = require('./nameList')
const enableConsumableHandler = require('./enable')
const disableConsumableHandler = require('./disable')

const router = require('express').Router()

router.use(admintokenAuth)
router.use(enableConsumableHandler)
router.use(listConsumableHandler)
router.use(createConsumableHandler)
router.use(deleteConsumableHandler)
router.use(disableConsumableHandler)
router.use(updateConsumableHandler)
router.use(updateConsumablePurchaseHandler)
router.use(assignConsumableHandler)
router.use(listConsumableNameHandler)
router.get("/entirehistory", entireHistoryConsumableHandler)
router.post("/history", historyConsumableHandler)

module.exports = exports = router